import pandas as pd

# Criação do dicionário de dados com as questões e alternativas
data = {
    "Questão": list(range(31, 51)),
    "Enunciado": [
        "Agricultura Familiar é a principal responsável pela produção dos alimentos que são disponibilizados para o consumo da população brasileira. A maioria das definições da agricultura familiar está vinculada ao número de empregados, ao tamanho da propriedade e a origem da fonte de renda. No Brasil, foram definidos alguns critérios que determinam o pertencimento, ou não, de uma produção agrícola em um contexto familiar. As normas foram estabelecidas em função do Programa Nacional de Fortalecimento da Agricultura Familiar – PRONAF. De acordo com o PRONAF e os conhecimentos acerca da agricultura familiar, analise as afirmativas abaixo. I. Para ser considerado agricultor familiar 80% da renda líquida deve ser proveniente da exploração agropecuária da propriedade. II. Deve explorar parcela de terra na condição de proprietário, posseiro, arrendatário, comodatário, parceiro, concessionário do Programa Nacional de Reforma Agrária (PNRA) ou permissionário de áreas públicas. III. Não pode deter, a qualquer título, área superior a 4 (quatro) módulos fiscais (que não varia conforme o município e a proximidade maior ou menor com as zonas urbana e rural). IV. Deve ter o trabalho familiar como predominante na exploração do estabelecimento, utilizando mão de obra de terceiros de acordo com as exigências sazonais da atividade agropecuária, podendo manter empregados permanentes em número menor ou igual ao número de pessoas da família ocupadas com o empreendimento familiar. V. Deve residir no estabelecimento ou em local próximo, considerando as características geográficas regionais. Assinale a alternativa correta.",
        "Ao analisar a produção agrícola da cultura do milho e da soja é possível verificar que existe uma interrelação a montante com a produção de insumos e prestação de serviços e a jusante com agroindústrias e a produção animal (suínos, aves, bovinos, são alguns exemplos). Levando em consideração os conhecimentos sobre agronegócio, cadeia produtiva e sistemas de arranjos produtivos locais, assinale a alternativa correta.",
        "O crescimento e desenvolvimento da agropecuária brasileira passa necessariamente por medidas que visem o desenvolvimento sustentável, como as de proteção do meio ambiente. Considerando as Áreas de Preservação Permanentes (APPs) e os conhecimentos sobre a preservação das matas ciliares, assinale a alternativa correta.",
        "Dentre as estratégias para a conservação da biodiversidade está a criação de corredores ecológicos para a integração em rede das Unidades de Conservação (UC), que sofrem com isolamento ao longo do tempo. Sobre o papel das UC e os corredores ecológicos, assinale a alternativa incorreta.",
        "Uma ______, tem características ou ______ que compartilha com organismos componentes, com o ciclo que cresce, se diferencia e se mantém, como acontece com o organismo. Há também características próprias do grupo ou ______, exemplos são taxa de natalidade, mortalidade proporção de idades e a capacidade genéticas. Assinale a alternativa que preencha correta e respectivamente as lacunas.",
        "Para as raízes retirarem os nutrientes do solo, existe um grande desenvolvimento radicular nas plantas, garantindo o maior contato possível com o maior volume de solo. A respeito da concentração dos nutrientes no sistema solo-planta, analise as afirmativas a seguir. I. Em condições normais, as concentrações de nutrientes nas plantas excedem as concentrações no solo. Experimento realizado com a cultura da cenoura demonstrou que a concentração do K+ nos tecidos é 10 mil vezes maior do que a concentração na solução imersa. II. Os íons podem se deslocar de um ambiente para o outro (do solo para a raiz, por exemplo) desde que se obedeça aos gradientes de concentração dos nutrientes. III. No transporte passivo de íons ocorre um gasto indireto de energia metabólica, sendo isso possível por causa da hidrólise do ATP, em um sítio diferente daquele em que ocorre o transporte do íon. IV. No transporte ativo, a energia é utilizada de maneira direta pelo transportador, como é o caso das bombas iônicas, ou indireta, por meio da geração de gradientes de prótons. V. A bomba de extrusão de prótons é um mecanismo desenvolvido pelas plantas capaz de evitar o gasto energético a fim de permitir a entrada de espécies iônicas nas células. Assinale a alternativa correta.",
        "As Substâncias Húmicas (SH) são de natureza química fundamentalmente orgânica, presentes em águas, solos e sedimentos. São formadas a partir da humificação da matéria orgânica fresca depositada. Em quais processos as SH afetam as plantas. Assinale a alternativa correta.",
        "A razão entre o Carbono e o Nitrogênio presente no solo é conhecida como relação C/N, sendo a proporção desses elementos dependente do resíduo deixado pela biomassa de uma cultura. A respeito dessa relação, assinale a alternativa incorreta.",
        "A colheita é a última operação realizada no campo, no processo de produção agrícola. A colheita de cereais envolve as etapas de ______. Assinale a alternativa que preencha corretamente a lacuna e que descreva a sequência realizada para a colheita de grãos.",
        "A respeito dos diferentes sistemas de irrigação utilizados nas culturas, a escolha do melhor modelo deve levar em consideração a qualidade e disponibilidade da água, mão de obra, topografia, entre outros. A respeito dos sistemas de irrigação mais utilizados, assinale a alternativa correta.",
        "Com relação a forma de aplicação e ao mecanismo de ação, os herbicidas podem ser classificados em aplicação via solo, aplicação nas folhas (contato) ou aplicação via folha (sistêmico). Em relação aos herbicidas aplicados via solo, analise as afirmativas a seguir. I. Aplicados ao solo – se movem a partir das raízes através de canais de absorção específicos, como proteínas ATPases. Os exemplos de herbicidas deste grupo são os carbamotioatos. II. Aplicados ao solo – são muito dependentes do teor de água no solo. Se o solo estiver seco serão pouco efetivos porque sua dissolução na solução do solo será pequena. Inibidores de síntese de pigmentos carotenóides são exemplos de herbicidas deste grupo. III. Aplicados ao solo - Os inibidores de crescimento de plântulas interrompem o crescimento e desenvolvimento das plântulas. Incluem os inibidores de parte aérea e raízes (dinitroanilinas) e a formação dos microtúbulos (acetamidas). IV. Aplicados ao solo – Os herbicidas de acetamidas são usados em pré-emergência ou incorporados para controle de gramíneas anuais. Porém não controlam plantas que já tenham emergido. Assinale a alternativa correta.",
        "Os princípios de whetzel surgiram para sistematizar os métodos de controle existentes. Esses princípios são definidos e interagem no ciclo das relações patógeno-hospedeiro. Conforme os princípios, analise a figura 1, e assinale a alternativa que preencha corretamente as lacunas da imagem.",
        "A adoção de medidas, pelos armazenadores, para evitar danos causados por pragas é possível com o uso do Manejo Integrado de Pragas (MIP), que também é aplicado no caso de grãos armazenados. Sobre o MIP em grãos armazenados, assinale a alternativa incorreta.",
        "O feijoeiro comum (Phaseolus vulgaris L.) é um dos mais importantes grãos consumidos no Brasil. A respeito do centro de origem dessa cultura, assinale a alternativa correta.",
        "A alface (Lactuca sativa) representa uma das folhosas mais consumidas na forma de salada. As folhas crescem nos caules diminutos em forma de roseta e pode variar em relação a textura da folha, a formação ou não de “cabeça” e a coloração. Sobre a cultura da alface, assinale a alternativa correta.",
        "Sobre a cultura do cajueiro (Anacardium occidentale L.), o cajueiro-anão, e as podas realizadas nessa cultura para melhor condução, analise as afirmativas a seguir. I. A desbrota é uma operação realizada durante o estabelecimento da cultura, retirando-se os brotos que nascem logo após o período chuvoso a partir do terceiro ano de cultivo, quando a planta já está estabelecida. II. Retirada da panícula – o cajueiro-anão é precoce, sendo assim, é possível haver emissão de panículas florais ainda no primeiro ano ou até mesmo em época de viveiro. É recomendada a retirada destas panículas nesta fase, por constituem um desvio de energia. III. As podas são divididas em: Formação, Limpeza e manutenção. São indicadas por garantir um máximo rendimento econômico. A poda de limpeza é a mais utilizada no período após a safra para remoção dos ramos secos, caídos ou praguejados. IV. Já nas primeiras produções, uma poda para facilitar a colheita, é recomendada. Em alguns casos, chega a ser erroneamente drástica, para permitir a passagem de máquinas. Sendo a frutificação do cajueiro periférica, predominantemente nos 2/3 inferiores da planta, deve-se evitar a eliminação excessiva desses ramos. Assinale a alternativa correta.",
        "O Enxofre (S) é um dos elementos fundamentais para o desenvolvimento das plantas. É um elemento que sofre com transformações a depender do tipo do solo em que se encontra. Sobre o elemento e as transformações que este sofre, assinale a alternativa correta.",
        "A amostragem de solo é a primeira etapa de um bom programa de adubação e calagem. Assim, a correta amostragem garante precisão nos resultados da análise. Dessa maneira, sobre a amostragem de solo, analise as afirmativas a seguir. I. Dividir a propriedade em glebas homogêneas, nunca superiores a 20 hectares, amostrando cada área isoladamente. Separar as glebas com a mesma posição topográfica, cor do solo, textura, cultura ou vegetação anterior. II. As ferramentas para a amostragem de solo podem ser variadas, sendo a enxada amplamente difundida e utilizada pelos produtores. Deve-se fazer um buraco em forma de cunha no solo com profundidade de 10 cm, não sendo recomendada a retirada de amostras de solos mais profundos. III. Realizar subamostras da gleba, a fim de se obter uma média da área amostrada. Para isso, percorrer a área escolhida em reta e coletar 5 subamostras por gleba homogênea. Em cada ponto amostrado incorporar o material da superfície ao solo e retirar uma amostra. IV. Transferir a terra de cada subamostra para um balde ou outro recipiente limpo. Repetir a amostragem do mesmo modo em cada um dos pontos. Quebrar os torrões de terra dentro do balde, retirar pedras, gravetos ou outros resíduos, e misturar muito bem. Se a amostra estiver muito úmida, deixar secar ao ar. Retirar cerca de 300 g de terra do balde e transferir para uma caixa de papelão apropriada para análise de solo ou saco plástico limpo. Assinale a alternativa correta.",
        "Levando em consideração os conhecimentos sobre fertilidade do solo, analise a frase a seguir. A ______, diz que o rendimento de uma colheita é limitado pela ausência de qualquer um dos nutrientes essenciais, mesmo que todos os demais estejam disponíveis em quantidades adequadas. Assinale a alternativa que preencha corretamente a lacuna.",
        "Levando em consideração os conhecimentos sobre microbiologia do solo, leia o texto a seguir. A fração morta da matéria orgânica do solo pode ser dividida em dois componentes: Matéria orgânica em estádios iniciais de decomposição, na qual a morfologia do material vegetal de origem é ainda identificada; e material em fase avançada de decomposição, conhecido como, ______, em que não é possível visualizar vestígios morfológicos do material que o originou. Assinale a alternativa que preencha corretamente a lacuna."
    ],
    "a)": [
        "Apenas as afirmativas I, III e IV estão corretas",
        "Clusters agroindustriais mostram as integrações e interrelações entre cadeias do agronegócio. Qualquer empreendimento econômico não pode ser restrito a determinado sistema agroindustrial isolado, porque existe interdependência entre sistemas dentro de determinado espaço. Exemplo disso é a interrelação entre a cadeia produtiva da cultura do milho e da soja.",
        "A APP é uma área protegida por lei quando coberta por vegetação nativa e possui funções ambientais de preservar os recursos hídricos a estabilidade geológica e a biodiversidade local, promovendo e facilitando o fluxo gênico de fauna e flora.",
        "Para a implantação de um corredor ecológico é preciso levar em consideração uma série de aspectos, sendo os físico-naturais um exemplo. Os aspectos físico-naturais estão relacionados com as características do quadro físico-natural da paisagem. São geralmente empregados dados sobre relevo (altimetria e declividade, principalmente), e solos (aptidão agrícola e susceptibilidade à erosão). A partir desses dados são indicadas como potenciais, por exemplo, as áreas que apresentam baixa aptidão agrícola e/ou estão mais susceptíveis a processos erosivos.",
        "população / informações genéticas / potencial biótico",
        "Apenas as afirmativas I, IV e V estão corretas",
        "As SH têm efeito sobre os processos de sinalização celular, de nutrição e de proteção antiestresse mediante mecanismos de ação diretos e indiretos",
        "Um solo com baixa relação C/N apresenta predomínio do processo de mineralização do N em relação ao processo de imobilização",
        "Alimentação, Corte, Separação, Trilha e Limpeza",
        "A irrigação por aspersão é um método que exige sistematização do terreno, a instalação pode ser dispendiosa em culturas já estabelecidas, no entanto possui como vantagem o fato da distribuição da água não ser afetada pelo vento",
        "Apenas as afirmativas I, III e IV estão corretas",
        "1. Erradicação; 2. Exclusão; 3. Proteção; 4. Imunização; 5. Terapia",
        "Caso os grãos fiquem armazenados por um período superior a 90 dias será necessário o uso de medidas de controle, a fim de evitar ataques de pragas. É recomendado nesse caso a transferência dos grãos de um silo para outro, para que possa ser realizada uma limpeza com o uso de inseticidas polvilhados na estrutura.",
        "A Faseolina é a principal proteína que distingue os tipos de feijão, estando presente nos grãos pequenos de origem central das Américas e ausente nos grãos andinos",
        "A saturação de base para a alface deve estar em torno de 70%, dessa forma é recomendada a realização da calagem quando necessária. O potássio (K) é o elemento mais limitante para a cultura e deve ser aplicado em quantia significativa.",
        "Apenas as afirmativas II e III estão corretas",
        "A calagem aumenta a Capacidade de Troca de Cátios (CTC) no solo, o que também promove um aumento da quantia de S nos colóides do solo",
        "Apenas as afirmativas I e IV estão corretas",
        "lei do mínimo de liebig",
        "húmus"
    ],
    "b)": [
        "Apenas as afirmativas II, IV e V estão corretas",
        "As vantagens dos clusters, em relação a sistemas isolados, são justamente as possibilidades de junção de cadeias produtivas, fazendo com que a competitividade entre estas cadeias não ocorra, uma vez que os sistemas produtivos funcionam, apenas de maneira conjunta, evitando o isolamento das empresas",
        "As faixas marginais de cursos d’água naturais e perenes, excluindo os efêmeros e intermitentes, desde a borda da calha do leito regular são consideradas APPs",
        "Os corredores ecológicos também possuem objetivos sociais, tais como: proteção da biodiversidade e dos recursos hídricos, recreação, coesão cultural e de comunidades, aumento da produtividade agroflorestal",
        "população / informações genéticas / atributos de grupo",
        "Apenas as afirmativas II, III e IV estão corretas",
        "Os efeitos diretos das SH ocorrem por meio de sua participação no fornecimento de nutrientes, no aumento da população microbiana e da Capacidade de Troca de Cátions (CTC)",
        "Um solo com baixa relação C/N apresenta predomínio do processo de imobilização do N em relação ao processo de mineralização",
        "Limpeza, Alimentação, Corte, Trilha e Separação",
        "A escolha do aspersor para a irrigação por aspersão leva em consideração a lâmina de água fornecida, diâmetro do bocal e espaçamento entre aspersores",
        "Apenas as afirmativas II, III e IV estão corretas",
        "1. Exclusão; 2. Erradicação; 3. Imunização; 4. Proteção; 5. Terapia",
        "O uso adequado de medidas de limpeza pode definir o sucesso do controle das pragas de grãos armazenados. A eliminação total de focos de infestação dentro da unidade, como resíduos de grãos, poeiras e sobras de classificação, permitirá o armazenamento adequado. Após essa limpeza, o tratamento periódico de toda a estrutura armazenadora, com inseticidas protetores de longa duração, é uma necessidade para evitar reinfestação de insetos.",
        "O feijão é cultivado em uma grande diversidade de ambientes, e por essa maneira possui uma variabilidade de caracteres agronômicos grande, não havendo, no entanto, grande diversidade genética entre os tipos de grãos",
        "A forma de implantação da cultura mais comum é por meio de mudas, sendo estas iniciadas em bandejas e posteriormente, quando apresentarem 4 folhas definitivas, transplantadas para o canteiro. O espaçamento utilizado comumente é de 25-30 cm x 25-30 cm.",
        "Apenas as afirmativas I, III e IV estão corretas",
        "As principais causas de deficiência de S nos solos tropicais estão associadas a forma em que o elemento se apresenta no solo. Quando em forma de sulfato a disponibilidade do nutriente é menor",
        "Apenas as afirmativas I, III e IV estão corretas",
        "produção da cultura",
        "biomassa do solo"
    ],
    "c)": [
        "Apenas as afirmativas III e IV estão corretas",
        "Um Arranjo Produtivo Local (APL) não pode ser considerado uma visão de cluster, porque não existe uma interrelação com outras cadeias produtivas. Existe apenas uma cadeia sendo trabalhada em seus setores resultando em uma rede com os segmentos-chave de um determinado produto",
        "A APP de um rio que tem 15 metros de largura será de, no mínimo, 50 metros medidos a partir da borda da calha do leito regular desse rio",
        "Dentre as funções ecológicas dos corredores ecológicos está a de servir de habitat para os animais",
        "densidade populacional / atributos biológicos / propriedades",
        "Apenas as afirmativas I, II, III e IV estão corretas",
        "Os efeitos indiretos das SH ocorrem pela regulação dessas substâncias em processos metabólicos das plantas. Como exemplo, cita-se a mimetização dessas estruturas húmicas em fitormônios que podem ser reconhecidos pelos receptores da auxina",
        "O Biochar ou carvão vegetal, é resistente a decomposição e seu emprego como condicionador de solo está relacionado ao aumento do conteúdo de C e atributos químicos, físicos e biológicos",
        "Alimentação, Corte, Trilha, Limpeza e Separação",
        "Na microaspersão, a água é trabalhada com pressões menores que no gotejamento, sendo os orifícios de saída da água menores que no gotejamento",
        "Apenas as afirmativas I, II e IV estão corretas",
        "1. Exclusão; 2. Erradicação; 3. Imunização; 4. Terapia; 5. Proteção",
        "As pragas que atacam os diferentes tipos de grãos devem ser identificadas taxonomicamente, pois dessa identificação dependerão as medidas de controle a serem tomadas e a consequente potencialidade de destruição dos grãos. As pragas de grãos armazenados podem ser divididas em dois grupos de maior importância econômica, que são os besouros e as traças",
        "O feijão teve dois principais centros de domesticação. América central e México, que originou a maioria dos grãos pequenos. O segundo centro de origem provável foi na região andina, norte da Argentina e sul do Peru, dando origem aos grãos graúdos",
        "A cultura não é muito exigente em água, portanto irrigação deve ser realizada com cautela, a fim de evitar o apodrecimento de raízes e folhas mais próximas do solo",
        "Apenas as afirmativas I, II e IV estão corretas",
        "Uma das poucas formas práticas de reduzir o pH do solo é através do uso de S elementar. Com a redução do S elementar, esta passa para a forma de sulfeto e com isso ocorre uma reação que causa acidez",
        "Apenas as afirmativas I, III e IV estão corretas",
        "quantidade de nutrientes",
        "composto"
    ],
    "d)": [
        "Apenas as afirmativas IV e V estão corretas",
        "Um Arranjo Produtivo Local (APL) é uma alternativa viável apenas para produtores rurais de porte médio, já que o APL irá gerenciar as ações de cada elo da cadeia produtiva. O pequeno produtor, por estar presente em uma cadeia produtiva curta, não se enquadra nas propostas de um sistema econômico desse porte",
        "Áreas no entorno de nascentes sempre serão consideradas APPs e devem ser preservadas com no mínimo 30 metros no raio",
        "Dentre as funções ecológicas dos corredores ecológicos está a de servir de fonte e ralo, ou seja, tem relação com a mortalidade e reprodução que pode existir no corredor",
        "densidade populacional / informações genéticas / atributos de grupo",
        "Apenas as afirmativas I, III e IV estão corretas",
        "As SH podem ser separadas em duas frações: ácidos fúlvicos (AF) e ácidos húmicos (AH). O AF é a fração solúvel em pH menor que 2, já o AH pode ser solúvel em qualquer valor de pH",
        "Em áreas onde há aporte significativo de N via fertilizante, a presença de fitomassa residual na superfície favorece a imobilização do nitrogênio em razão da elevada relação C/N",
        "Corte, Alimentação, Trilha, Separação e Limpeza",
        "Os gotejadores trabalham com pressões maiores que na microaspersão e foram desenvolvidos para aplicação de água em cultivos de casa, de vegetação ou plantas com maior distância de espaçamento como é o caso de pomares",
        "Apenas as afirmativas I e III estão corretas",
        "1. Exclusão; 2. Erradicação; 3. Imunização; 4. Proteção; 5. Terapia",
        "Uma vez armazenados, os grãos devem ser monitorados durante todo o período em que permanecerem estocados. O acompanhamento da evolução de pragas que ocorrem na massa de grãos armazenados é de fundamental importância, pois permite detectar o início de infestações que poderão alterar a qualidade final do grão",
        "Existe uma compatibilidade gênica entre os diferentes grupos de feijão, os mesoamericanos e os andinos. Por isso, é possível realizar livre cruzamento entre eles. Essa compatibilidade é relacionada a ação de dois genes, DL1 e DL2, que permite a formação de plantas mais desenvolvidas e altamente produtivas",
        "A “queima-marginal” é uma anomalia comum na alface, causada pelo desequilíbrio nutricional entre Ca e N. No entanto os meios de prevenção, como a calagem não são eficazes no controle desta anomalia",
        "Apenas as afirmativas III e IV estão corretas",
        "O sulfato é encontrado em solos mal drenados, e é a forma imobilizada do S orgânico, a transformação do sulfato em sulfeto através da redução, eleva o pH do solo",
        "Apenas as afirmativas II, III e IV estão corretas",
        "composição essencial",
        "Litera"
    ],
    "e)": [
        "Apenas as afirmativas I, II e IV estão corretas",
        "Um Arranjo Produtivo Local (APL) deve possuir um número significativo de empreendimentos no território e de indivíduos que atuam em torno de uma atividade produtiva predominante. Existe uma preocupação em desenvolver economicamente a atividade foco sem um mecanismo de governança, a fim de se evitar relações políticas e competições acirradas em torno de interesses monetários",
        "Áreas de Reserva Legal (RL) não são obrigatórias, diferente de APPs. A instalação de uma RL fica a critério do produtor e se caracteriza como área de uso econômico sustentável dos recursos naturais do imóvel rural para a conservação da biodiversidade",
        "Em vista da maior integração entre os remanescentes, o tipo de conectividade é levado em consideração. Seja essa integração estrutural, com relação ao quadro físico-natural, ou funcional, que levanta dados sobre movimentação de indivíduos e organismos ao longo da paisagem",
        "população / atributos biológicos / atributos de grupo",
        "Apenas as afirmativas I e V estão corretas",
        "A humina (Hu) é a redefinição que as SH sofrem ao serem submetidas a qualquer valor de pH",
        "Organossolos com relação C/N muito elevada (pouco decompostos) a maior parte do N fica indisponível, por isso necessitam de elevadas doses de adubos nitrogenados",
        "Corte, Alimentação, Limpeza, Trilha e Separação",
        "A irrigação por inundação requer grande disponibilidade de água, o terreno deve ser plano e a capacidade de infiltração do solo deve ser alta. A capacidade de infiltração da água é um parâmetro altamente desejável para a viabilidade do manejo da irrigação no campo",
        "Apenas as afirmativas II e IV estão corretas",
        "1. Exclusão; 2. Erradicação; 3. Imunização; 4. Proteção; 5. Terapia",
        "A mudança de comportamento dos armazenadores é a fase inicial e mais importante de todo o processo. Nessa fase o alvo é conscientizar a equipe sobre a importância de pragas no armazenamento e os danos diretos e indiretos que podem causar",
        "O hábito de crescimento dos feijões é dividido em determinado, prostrado ou ereto.  O hábito determinado é exclusivo dos grãos andinos",
        "Podridão basal e queima-da-saia são exemplos de doenças fúngicas que afetam a cultura, mas não há cultivares tolerantes ou resistentes para tais doenças, por isso o controle deve ser de evitar o plantio sequenciado num mesmo canteiro de asteráceas e evitar o cultivo em época de secas, por apresentar maior incidência da doença",
        "Apenas as afirmativas I e II estão corretas",
        "Em solos bem drenados e arejados há um predomínio da forma oxidada, o sulfato, sendo esta forma, fonte primordial de S para as plantas",
        "Apenas a afirmativa IV está correta",
        "formulações de nutrientes",
        "frações particuladas"
    ]
}

# Criar DataFrame
df = pd.DataFrame(data)


# Salvar DataFrame em um arquivo Excel
file_path = 'C:/Users/Usuário/Desktop/questoes_concurso_publicoUFPB2023.xlsx'
df.to_excel(file_path, index=False)
